### ISSUE TITLE
Halloween 2024 Update

### ISSUE THREAD

**Issue by Piras314** [Goob-Station/Goob-Station#714]
## Description

Update that will run on the server during Halloween! Development is on the Halloween-2024 branch and you can make pull requests to that branch by selecting that branch instead of "master" when making a pull request.

TODO, Suggestions, Etc. Comment if you want something added here
- [ ] HoD Antagging - #694 (PR needs to be redone)
- [ ] Creepy Clown Mask - #715 
- [ ] Lighting Changes - #724 
- [ ] Durk's Halloween Special - #725
